version: 2

refrences:
  ignored-branches: &ignored-branches
    branches:
      ignore:
        - gh-pages

  cache-options: &cache-options
    key: package-cache-{{ checksum "package.json" }}

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          <<: *cache-options
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: linter
          command: npm run lint
      - run:
          name: build
          command: ./node_modules/.bin/next build
      - run:
          name: postbuild
          command: npm run postbuild
      - run:
          name: test
          command: ./node_modules/.bin/jest tests --ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            <<: *ignored-branches

      - test:
          filters:
            <<: *ignored-branches
          requires:
            - build
